apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-svc
spec:
  selector:
    app: cicd-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP # Or LoadBalancer if on cloud
