apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
      - name: orders
        image: k8s.gcr.io/echoserver:1.10 # Simulate API with echoserver
        ports:
        - containerPort: 8080
