apiVersion: v1
kind: Service
metadata:
  name: orders-api-svc # Service name used for discovery
spec:
  selector:
    app: orders-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # Match echoserver container port
  type: ClusterIP
