apiVersion: v1
kind: Service
metadata:
  name: products-api-svc # Service name used for discovery
spec:
  selector:
    app: products-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
