# 3. Bind the User to the Role within the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: development # Binding applies only within 'development'
subjects:
- kind: User
  name: dev-user # Name is case-sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef: # The Role being granted
  kind: Role # Can be Role or ClusterRole
  name: pod-reader # Name of the Role created above
  apiGroup: rbac.authorization.k8s.io
