# 1. Define the Role (namespaced)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development # Role exists only in 'development' namespace
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"] # Allow access to pods and their logs
  verbs: ["get", "list", "watch"] # Read-only verbs
