# app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: simple-ui
  template:
    metadata:
      labels:
        app: simple-ui
    spec:
      containers:
      - name: ui
        image: nginx:1.21 # Initial version
        ports:
        - containerPort: 80
