apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1 # Start with 1 replica
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        # This image has apache and php, index.php simulates load
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources: # IMPORTANT: Set resource requests for HPA
          requests:
            cpu: 200m # Request 0.2 CPU core
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  selector:
    run: php-apache
  ports:
  - port: 80 # Service port
  # type: LoadBalancer # Optional: Use LoadBalancer if on cloud
  type: ClusterIP # Use ClusterIP + port-forward for local testing
