apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-ui-app
  namespace: argocd # Deploy the Application object into Argo CD's namespace
spec:
  project: default # Use the default Argo CD project
  source:
    repoURL: https://github.com/your-username/my-gitops-app.git # !!! REPLACE with your repo URL !!!
    targetRevision: HEAD # Track the latest commit on the default branch (main)
    path: app # Directory within the repo containing manifests
  destination:
    server: https://kubernetes.default.svc # Deploy to the same cluster Argo CD is in
    namespace: default # Deploy the application into the 'default' namespace
  syncPolicy: # Configure automatic synchronization
    automated:
      prune: true # Delete resources that are removed from Git
      selfHeal: true # Automatically sync if cluster state drifts from Git
    syncOptions:
    - CreateNamespace=true # Automatically create the destination namespace if it doesn't exist
