apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-sa-pod-reader-binding
  namespace: restricted-ns
subjects:
- kind: ServiceAccount
  name: limited-sa
  namespace: restricted-ns
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io
