apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: restricted-ns # Deploy into the restricted namespace
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      privileged: true # This violates the 'restricted' standard
