apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: echoserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echo-container
        image: k8s.gcr.io/echoserver:1.10 # Initial version
        ports:
        - containerPort: 8080
        readinessProbe: # Essential for smooth rolling updates
          httpGet:
            path: / # echoserver responds to /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service # Expose the deployment internally
metadata:
  name: echo-service
spec:
  selector:
    app: echoserver # Selects pods managed by the deployment
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 8080 # Container port
  type: ClusterIP # Internal access only for now
