# (Remember to base64 encode the values)
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  # echo -n 'admin-user' | base64 -> YWRtaW4tdXNlcg==
  username: YWRtaW4tdXNlcg==
  # echo -n 'verySecretKey123' | base64 -> dmVyeVNlY3JldEtleTEyMw==
  api.key: dmVyeVNlY3JldEtleTEyMw==
