apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # Same name as in Chapter 1 lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.21 # Specify a version
        ports:
        - containerPort: 80
