apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted read-write by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 Gibibyte of storage
  # storageClassName: standard # Optional: Request a specific storage class
---
apiVersion: v1
kind: Pod
metadata:
  name: my-storage-pod
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /data/output.log; sleep 5; done"]
    volumeMounts:
    - name: my-storage # Must match volume name below
      mountPath: /data # Mount path inside the container
  volumes:
  - name: my-storage # Volume name referenced by volumeMounts
    persistentVolumeClaim:
      claimName: my-pvc # Reference the PVC created above
