apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Selects pods with the label app=nginx
  ports:
    - protocol: TCP
      port: 80       # Port the service is available on within the cluster
      targetPort: 80 # Port the container is listening on
  type: ClusterIP # Or NodePort, LoadBalancer
