apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  containers:
  - name: nginx-resourced
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests: # Minimum guaranteed resources
        memory: "64Mi" # 64 Mebibytes
        cpu: "250m"    # 0.25 CPU core
      limits:   # Maximum allowed resources
        memory: "128Mi" # 128 Mebibytes
        cpu: "500m"     # 0.5 CPU core
