apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.stable.example.com # <plural>.<group>
spec:
  group: stable.example.com
  scope: Namespaced # Resource will exist within namespaces
  names:
    plural: webapps
    singular: webapp
    kind: WebApp # Kind used in manifests
    shortNames:
    - wa
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  description: "Container image for the web app"
                replicas:
                  type: integer
                  minimum: 1
                  description: "Number of desired replicas"
                port:
                  type: integer
                  default: 8080
                  description: "Container port to expose"
                configMapName: # Example: Reference another K8s object
                  type: string
                  description: "Name of the ConfigMap holding app settings"
              required: ["image", "replicas"] # image and replicas are mandatory
            status: # Define a simple status sub-resource
              type: object
              properties:
                availableReplicas:
                  type: integer
                url:
                  type: string
      # Enable the status sub-resource
      subresources:
        status: {}
