apiVersion: v1
kind: Service # Headless Service for stable network IDs
metadata:
  name: nginx-headless
spec:
  clusterIP: None # Makes it headless
  selector:
    app: nginx-sts # Selects pods managed by the StatefulSet
  ports:
  - port: 80
    name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx-headless" # Associate with the headless service
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sts # Must match template labels
  template: # Pod template
    metadata:
      labels:
        app: nginx-sts
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www-storage # Mount the volume created from template
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # Template for creating PVCs per Pod
  - metadata:
      name: www-storage # Name used in volumeMounts
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "your-storage-class" # Specify if needed
      resources:
        requests:
          storage: 1Gi
