apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
data:
  init.sh: |
    #!/bin/bash
    set -e
    # Simple script placeholder - real HA setup is more complex
    # involving replication configuration based on ordinal index etc.
    echo "Initializing PostgreSQL instance..."
    # In a real setup, check if $PGDATA is empty, run initdb if needed,
    # configure replication based on hostname (e.g., postgres-db-0 is primary)
    # For this lab, we assume the image entrypoint handles basic init.
    ls -l $PGDATA
    echo "Initialization script finished."
